package com.ssdkj.bbs.modular.model;

import java.util.ArrayList;
import java.util.List;

public class ArticleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbggenerated Thu Oct 10 10:23:40 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbggenerated Thu Oct 10 10:23:40 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbggenerated Thu Oct 10 10:23:40 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Oct 10 10:23:40 CST 2019
     */
    public ArticleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Oct 10 10:23:40 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Oct 10 10:23:40 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Oct 10 10:23:40 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Oct 10 10:23:40 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Oct 10 10:23:40 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Oct 10 10:23:40 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Oct 10 10:23:40 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Oct 10 10:23:40 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Oct 10 10:23:40 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Oct 10 10:23:40 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbggenerated Thu Oct 10 10:23:40 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andArticleIdIsNull() {
            addCriterion("articleId is null");
            return (Criteria) this;
        }

        public Criteria andArticleIdIsNotNull() {
            addCriterion("articleId is not null");
            return (Criteria) this;
        }

        public Criteria andArticleIdEqualTo(Long value) {
            addCriterion("articleId =", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotEqualTo(Long value) {
            addCriterion("articleId <>", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdGreaterThan(Long value) {
            addCriterion("articleId >", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdGreaterThanOrEqualTo(Long value) {
            addCriterion("articleId >=", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdLessThan(Long value) {
            addCriterion("articleId <", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdLessThanOrEqualTo(Long value) {
            addCriterion("articleId <=", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdIn(List<Long> values) {
            addCriterion("articleId in", values, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotIn(List<Long> values) {
            addCriterion("articleId not in", values, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdBetween(Long value1, Long value2) {
            addCriterion("articleId between", value1, value2, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotBetween(Long value1, Long value2) {
            addCriterion("articleId not between", value1, value2, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleTagIsNull() {
            addCriterion("articleTag is null");
            return (Criteria) this;
        }

        public Criteria andArticleTagIsNotNull() {
            addCriterion("articleTag is not null");
            return (Criteria) this;
        }

        public Criteria andArticleTagEqualTo(Integer value) {
            addCriterion("articleTag =", value, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagNotEqualTo(Integer value) {
            addCriterion("articleTag <>", value, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagGreaterThan(Integer value) {
            addCriterion("articleTag >", value, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagGreaterThanOrEqualTo(Integer value) {
            addCriterion("articleTag >=", value, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagLessThan(Integer value) {
            addCriterion("articleTag <", value, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagLessThanOrEqualTo(Integer value) {
            addCriterion("articleTag <=", value, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagLike(Integer value) {
            addCriterion("articleTag like", value, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagNotLike(Integer value) {
            addCriterion("articleTag not like", value, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagIn(List<Integer> values) {
            addCriterion("articleTag in", values, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagNotIn(List<Integer> values) {
            addCriterion("articleTag not in", values, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagBetween(Integer value1, Integer value2) {
            addCriterion("articleTag between", value1, value2, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagNotBetween(Integer value1, Integer value2) {
            addCriterion("articleTag not between", value1, value2, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTypeIsNull() {
            addCriterion("articleType is null");
            return (Criteria) this;
        }

        public Criteria andArticleTypeIsNotNull() {
            addCriterion("articleType is not null");
            return (Criteria) this;
        }

        public Criteria andArticleTypeEqualTo(Integer value) {
            addCriterion("articleType =", value, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeNotEqualTo(Integer value) {
            addCriterion("articleType <>", value, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeGreaterThan(Integer value) {
            addCriterion("articleType >", value, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("articleType >=", value, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeLessThan(Integer value) {
            addCriterion("articleType <", value, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeLessThanOrEqualTo(Integer value) {
            addCriterion("articleType <=", value, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeIn(List<Integer> values) {
            addCriterion("articleType in", values, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeNotIn(List<Integer> values) {
            addCriterion("articleType not in", values, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeBetween(Integer value1, Integer value2) {
            addCriterion("articleType between", value1, value2, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("articleType not between", value1, value2, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdIsNull() {
            addCriterion("articleAuthorId is null");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdIsNotNull() {
            addCriterion("articleAuthorId is not null");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdEqualTo(Long value) {
            addCriterion("articleAuthorId =", value, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdNotEqualTo(Long value) {
            addCriterion("articleAuthorId <>", value, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdGreaterThan(Long value) {
            addCriterion("articleAuthorId >", value, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("articleAuthorId >=", value, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdLessThan(Long value) {
            addCriterion("articleAuthorId <", value, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdLessThanOrEqualTo(Long value) {
            addCriterion("articleAuthorId <=", value, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdIn(List<Long> values) {
            addCriterion("articleAuthorId in", values, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdNotIn(List<Long> values) {
            addCriterion("articleAuthorId not in", values, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdBetween(Long value1, Long value2) {
            addCriterion("articleAuthorId between", value1, value2, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdNotBetween(Long value1, Long value2) {
            addCriterion("articleAuthorId not between", value1, value2, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andNickNameIsNull() {
            addCriterion("nickName is null");
            return (Criteria) this;
        }

        public Criteria andNickNameIsNotNull() {
            addCriterion("nickName is not null");
            return (Criteria) this;
        }

        public Criteria andNickNameEqualTo(String value) {
            addCriterion("nickName =", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotEqualTo(String value) {
            addCriterion("nickName <>", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameGreaterThan(String value) {
            addCriterion("nickName >", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameGreaterThanOrEqualTo(String value) {
            addCriterion("nickName >=", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLessThan(String value) {
            addCriterion("nickName <", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLessThanOrEqualTo(String value) {
            addCriterion("nickName <=", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLike(String value) {
            addCriterion("nickName like", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotLike(String value) {
            addCriterion("nickName not like", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameIn(List<String> values) {
            addCriterion("nickName in", values, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotIn(List<String> values) {
            addCriterion("nickName not in", values, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameBetween(String value1, String value2) {
            addCriterion("nickName between", value1, value2, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotBetween(String value1, String value2) {
            addCriterion("nickName not between", value1, value2, "nickName");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlIsNull() {
            addCriterion("headImgurl is null");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlIsNotNull() {
            addCriterion("headImgurl is not null");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlEqualTo(String value) {
            addCriterion("headImgurl =", value, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlNotEqualTo(String value) {
            addCriterion("headImgurl <>", value, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlGreaterThan(String value) {
            addCriterion("headImgurl >", value, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlGreaterThanOrEqualTo(String value) {
            addCriterion("headImgurl >=", value, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlLessThan(String value) {
            addCriterion("headImgurl <", value, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlLessThanOrEqualTo(String value) {
            addCriterion("headImgurl <=", value, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlLike(String value) {
            addCriterion("headImgurl like", value, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlNotLike(String value) {
            addCriterion("headImgurl not like", value, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlIn(List<String> values) {
            addCriterion("headImgurl in", values, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlNotIn(List<String> values) {
            addCriterion("headImgurl not in", values, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlBetween(String value1, String value2) {
            addCriterion("headImgurl between", value1, value2, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlNotBetween(String value1, String value2) {
            addCriterion("headImgurl not between", value1, value2, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountIsNull() {
            addCriterion("articleCommentCount is null");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountIsNotNull() {
            addCriterion("articleCommentCount is not null");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountEqualTo(Integer value) {
            addCriterion("articleCommentCount =", value, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountNotEqualTo(Integer value) {
            addCriterion("articleCommentCount <>", value, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountGreaterThan(Integer value) {
            addCriterion("articleCommentCount >", value, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("articleCommentCount >=", value, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountLessThan(Integer value) {
            addCriterion("articleCommentCount <", value, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountLessThanOrEqualTo(Integer value) {
            addCriterion("articleCommentCount <=", value, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountIn(List<Integer> values) {
            addCriterion("articleCommentCount in", values, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountNotIn(List<Integer> values) {
            addCriterion("articleCommentCount not in", values, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountBetween(Integer value1, Integer value2) {
            addCriterion("articleCommentCount between", value1, value2, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountNotBetween(Integer value1, Integer value2) {
            addCriterion("articleCommentCount not between", value1, value2, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountIsNull() {
            addCriterion("articleViewCount is null");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountIsNotNull() {
            addCriterion("articleViewCount is not null");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountEqualTo(Integer value) {
            addCriterion("articleViewCount =", value, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountNotEqualTo(Integer value) {
            addCriterion("articleViewCount <>", value, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountGreaterThan(Integer value) {
            addCriterion("articleViewCount >", value, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("articleViewCount >=", value, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountLessThan(Integer value) {
            addCriterion("articleViewCount <", value, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountLessThanOrEqualTo(Integer value) {
            addCriterion("articleViewCount <=", value, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountIn(List<Integer> values) {
            addCriterion("articleViewCount in", values, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountNotIn(List<Integer> values) {
            addCriterion("articleViewCount not in", values, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountBetween(Integer value1, Integer value2) {
            addCriterion("articleViewCount between", value1, value2, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountNotBetween(Integer value1, Integer value2) {
            addCriterion("articleViewCount not between", value1, value2, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticleParseCountIsNull() {
            addCriterion("articleParseCount is null");
            return (Criteria) this;
        }

        public Criteria andArticleParseCountIsNotNull() {
            addCriterion("articleParseCount is not null");
            return (Criteria) this;
        }

        public Criteria andArticleParseCountEqualTo(Integer value) {
            addCriterion("articleParseCount =", value, "articleParseCount");
            return (Criteria) this;
        }

        public Criteria andArticleParseCountNotEqualTo(Integer value) {
            addCriterion("articleParseCount <>", value, "articleParseCount");
            return (Criteria) this;
        }

        public Criteria andArticleParseCountGreaterThan(Integer value) {
            addCriterion("articleParseCount >", value, "articleParseCount");
            return (Criteria) this;
        }

        public Criteria andArticleParseCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("articleParseCount >=", value, "articleParseCount");
            return (Criteria) this;
        }

        public Criteria andArticleParseCountLessThan(Integer value) {
            addCriterion("articleParseCount <", value, "articleParseCount");
            return (Criteria) this;
        }

        public Criteria andArticleParseCountLessThanOrEqualTo(Integer value) {
            addCriterion("articleParseCount <=", value, "articleParseCount");
            return (Criteria) this;
        }

        public Criteria andArticleParseCountIn(List<Integer> values) {
            addCriterion("articleParseCount in", values, "articleParseCount");
            return (Criteria) this;
        }

        public Criteria andArticleParseCountNotIn(List<Integer> values) {
            addCriterion("articleParseCount not in", values, "articleParseCount");
            return (Criteria) this;
        }

        public Criteria andArticleParseCountBetween(Integer value1, Integer value2) {
            addCriterion("articleParseCount between", value1, value2, "articleParseCount");
            return (Criteria) this;
        }

        public Criteria andArticleParseCountNotBetween(Integer value1, Integer value2) {
            addCriterion("articleParseCount not between", value1, value2, "articleParseCount");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopIsNull() {
            addCriterion("articlePutTop is null");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopIsNotNull() {
            addCriterion("articlePutTop is not null");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopEqualTo(Integer value) {
            addCriterion("articlePutTop =", value, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopNotEqualTo(Integer value) {
            addCriterion("articlePutTop <>", value, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopGreaterThan(Integer value) {
            addCriterion("articlePutTop >", value, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopGreaterThanOrEqualTo(Integer value) {
            addCriterion("articlePutTop >=", value, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopLessThan(Integer value) {
            addCriterion("articlePutTop <", value, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopLessThanOrEqualTo(Integer value) {
            addCriterion("articlePutTop <=", value, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopIn(List<Integer> values) {
            addCriterion("articlePutTop in", values, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopNotIn(List<Integer> values) {
            addCriterion("articlePutTop not in", values, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopBetween(Integer value1, Integer value2) {
            addCriterion("articlePutTop between", value1, value2, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopNotBetween(Integer value1, Integer value2) {
            addCriterion("articlePutTop not between", value1, value2, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticleSequenceIsNull() {
            addCriterion("articleSequence is null");
            return (Criteria) this;
        }

        public Criteria andArticleSequenceIsNotNull() {
            addCriterion("articleSequence is not null");
            return (Criteria) this;
        }

        public Criteria andArticleSequenceEqualTo(Integer value) {
            addCriterion("articleSequence =", value, "articleSequence");
            return (Criteria) this;
        }

        public Criteria andArticleSequenceNotEqualTo(Integer value) {
            addCriterion("articleSequence <>", value, "articleSequence");
            return (Criteria) this;
        }

        public Criteria andArticleSequenceGreaterThan(Integer value) {
            addCriterion("articleSequence >", value, "articleSequence");
            return (Criteria) this;
        }

        public Criteria andArticleSequenceGreaterThanOrEqualTo(Integer value) {
            addCriterion("articleSequence >=", value, "articleSequence");
            return (Criteria) this;
        }

        public Criteria andArticleSequenceLessThan(Integer value) {
            addCriterion("articleSequence <", value, "articleSequence");
            return (Criteria) this;
        }

        public Criteria andArticleSequenceLessThanOrEqualTo(Integer value) {
            addCriterion("articleSequence <=", value, "articleSequence");
            return (Criteria) this;
        }

        public Criteria andArticleSequenceIn(List<Integer> values) {
            addCriterion("articleSequence in", values, "articleSequence");
            return (Criteria) this;
        }

        public Criteria andArticleSequenceNotIn(List<Integer> values) {
            addCriterion("articleSequence not in", values, "articleSequence");
            return (Criteria) this;
        }

        public Criteria andArticleSequenceBetween(Integer value1, Integer value2) {
            addCriterion("articleSequence between", value1, value2, "articleSequence");
            return (Criteria) this;
        }

        public Criteria andArticleSequenceNotBetween(Integer value1, Integer value2) {
            addCriterion("articleSequence not between", value1, value2, "articleSequence");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeIsNull() {
            addCriterion("articleCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeIsNotNull() {
            addCriterion("articleCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeEqualTo(String value) {
            addCriterion("articleCreateTime =", value, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeNotEqualTo(String value) {
            addCriterion("articleCreateTime <>", value, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeGreaterThan(String value) {
            addCriterion("articleCreateTime >", value, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("articleCreateTime >=", value, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeLessThan(String value) {
            addCriterion("articleCreateTime <", value, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("articleCreateTime <=", value, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeLike(String value) {
            addCriterion("articleCreateTime like", value, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeNotLike(String value) {
            addCriterion("articleCreateTime not like", value, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeIn(List<String> values) {
            addCriterion("articleCreateTime in", values, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeNotIn(List<String> values) {
            addCriterion("articleCreateTime not in", values, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeBetween(String value1, String value2) {
            addCriterion("articleCreateTime between", value1, value2, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeNotBetween(String value1, String value2) {
            addCriterion("articleCreateTime not between", value1, value2, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateTimeIsNull() {
            addCriterion("articleUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateTimeIsNotNull() {
            addCriterion("articleUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateTimeEqualTo(String value) {
            addCriterion("articleUpdateTime =", value, "articleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateTimeNotEqualTo(String value) {
            addCriterion("articleUpdateTime <>", value, "articleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateTimeGreaterThan(String value) {
            addCriterion("articleUpdateTime >", value, "articleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("articleUpdateTime >=", value, "articleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateTimeLessThan(String value) {
            addCriterion("articleUpdateTime <", value, "articleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("articleUpdateTime <=", value, "articleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateTimeLike(String value) {
            addCriterion("articleUpdateTime like", value, "articleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateTimeNotLike(String value) {
            addCriterion("articleUpdateTime not like", value, "articleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateTimeIn(List<String> values) {
            addCriterion("articleUpdateTime in", values, "articleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateTimeNotIn(List<String> values) {
            addCriterion("articleUpdateTime not in", values, "articleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateTimeBetween(String value1, String value2) {
            addCriterion("articleUpdateTime between", value1, value2, "articleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("articleUpdateTime not between", value1, value2, "articleUpdateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableIsNull() {
            addCriterion("articleCommentable is null");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableIsNotNull() {
            addCriterion("articleCommentable is not null");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableEqualTo(Integer value) {
            addCriterion("articleCommentable =", value, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableNotEqualTo(Integer value) {
            addCriterion("articleCommentable <>", value, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableGreaterThan(Integer value) {
            addCriterion("articleCommentable >", value, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableGreaterThanOrEqualTo(Integer value) {
            addCriterion("articleCommentable >=", value, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableLessThan(Integer value) {
            addCriterion("articleCommentable <", value, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableLessThanOrEqualTo(Integer value) {
            addCriterion("articleCommentable <=", value, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableIn(List<Integer> values) {
            addCriterion("articleCommentable in", values, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableNotIn(List<Integer> values) {
            addCriterion("articleCommentable not in", values, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableBetween(Integer value1, Integer value2) {
            addCriterion("articleCommentable between", value1, value2, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableNotBetween(Integer value1, Integer value2) {
            addCriterion("articleCommentable not between", value1, value2, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleImgURLIsNull() {
            addCriterion("articleImgURL is null");
            return (Criteria) this;
        }

        public Criteria andArticleImgURLIsNotNull() {
            addCriterion("articleImgURL is not null");
            return (Criteria) this;
        }

        public Criteria andArticleImgURLEqualTo(String value) {
            addCriterion("articleImgURL =", value, "articleImgURL");
            return (Criteria) this;
        }

        public Criteria andArticleImgURLNotEqualTo(String value) {
            addCriterion("articleImgURL <>", value, "articleImgURL");
            return (Criteria) this;
        }

        public Criteria andArticleImgURLGreaterThan(String value) {
            addCriterion("articleImgURL >", value, "articleImgURL");
            return (Criteria) this;
        }

        public Criteria andArticleImgURLGreaterThanOrEqualTo(String value) {
            addCriterion("articleImgURL >=", value, "articleImgURL");
            return (Criteria) this;
        }

        public Criteria andArticleImgURLLessThan(String value) {
            addCriterion("articleImgURL <", value, "articleImgURL");
            return (Criteria) this;
        }

        public Criteria andArticleImgURLLessThanOrEqualTo(String value) {
            addCriterion("articleImgURL <=", value, "articleImgURL");
            return (Criteria) this;
        }

        public Criteria andArticleImgURLLike(String value) {
            addCriterion("articleImgURL like", value, "articleImgURL");
            return (Criteria) this;
        }

        public Criteria andArticleImgURLNotLike(String value) {
            addCriterion("articleImgURL not like", value, "articleImgURL");
            return (Criteria) this;
        }

        public Criteria andArticleImgURLIn(List<String> values) {
            addCriterion("articleImgURL in", values, "articleImgURL");
            return (Criteria) this;
        }

        public Criteria andArticleImgURLNotIn(List<String> values) {
            addCriterion("articleImgURL not in", values, "articleImgURL");
            return (Criteria) this;
        }

        public Criteria andArticleImgURLBetween(String value1, String value2) {
            addCriterion("articleImgURL between", value1, value2, "articleImgURL");
            return (Criteria) this;
        }

        public Criteria andArticleImgURLNotBetween(String value1, String value2) {
            addCriterion("articleImgURL not between", value1, value2, "articleImgURL");
            return (Criteria) this;
        }

        public Criteria andArticleStatusIsNull() {
            addCriterion("articleStatus is null");
            return (Criteria) this;
        }

        public Criteria andArticleStatusIsNotNull() {
            addCriterion("articleStatus is not null");
            return (Criteria) this;
        }

        public Criteria andArticleStatusEqualTo(Integer value) {
            addCriterion("articleStatus =", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusNotEqualTo(Integer value) {
            addCriterion("articleStatus <>", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusGreaterThan(Integer value) {
            addCriterion("articleStatus >", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("articleStatus >=", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusLessThan(Integer value) {
            addCriterion("articleStatus <", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusLessThanOrEqualTo(Integer value) {
            addCriterion("articleStatus <=", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusIn(List<Integer> values) {
            addCriterion("articleStatus in", values, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusNotIn(List<Integer> values) {
            addCriterion("articleStatus not in", values, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusBetween(Integer value1, Integer value2) {
            addCriterion("articleStatus between", value1, value2, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("articleStatus not between", value1, value2, "articleStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbggenerated do_not_delete_during_merge Thu Oct 10 10:23:40 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbggenerated Thu Oct 10 10:23:40 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}