package com.ssdkj.bbs.modular.model;

import com.ssdkj.bbs.common.annotation.Skip;

public class Comment {
    @Skip
    private int pageNum;
    @Skip
    private int pageSize;

    public int getPageNum() {
        return pageNum;
    }

    public void setPageNum(int pageNum) {
        this.pageNum = pageNum;
    }

    public int getPageSize() {
        return pageSize;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentId
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    private Long commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentContent
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    private String commentContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentCreateTime
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    private String commentCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentAuthorId
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    private Long commentAuthorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentNickName
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    private String commentNickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.headImgurl
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    private String headImgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.articleId
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentParseCount
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    private Integer commentParseCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentPutTop
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    private Integer commentPutTop;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentId
     *
     * @return the value of comment.commentId
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentId
     *
     * @param commentId the value for comment.commentId
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentContent
     *
     * @return the value of comment.commentContent
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentContent
     *
     * @param commentContent the value for comment.commentContent
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentCreateTime
     *
     * @return the value of comment.commentCreateTime
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public String getCommentCreateTime() {
        return commentCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentCreateTime
     *
     * @param commentCreateTime the value for comment.commentCreateTime
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public void setCommentCreateTime(String commentCreateTime) {
        this.commentCreateTime = commentCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentAuthorId
     *
     * @return the value of comment.commentAuthorId
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public Long getCommentAuthorId() {
        return commentAuthorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentAuthorId
     *
     * @param commentAuthorId the value for comment.commentAuthorId
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public void setCommentAuthorId(Long commentAuthorId) {
        this.commentAuthorId = commentAuthorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentNickName
     *
     * @return the value of comment.commentNickName
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public String getCommentNickName() {
        return commentNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentNickName
     *
     * @param commentNickName the value for comment.commentNickName
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public void setCommentNickName(String commentNickName) {
        this.commentNickName = commentNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.headImgurl
     *
     * @return the value of comment.headImgurl
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public String getHeadImgurl() {
        return headImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.headImgurl
     *
     * @param headImgurl the value for comment.headImgurl
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public void setHeadImgurl(String headImgurl) {
        this.headImgurl = headImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.articleId
     *
     * @return the value of comment.articleId
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.articleId
     *
     * @param articleId the value for comment.articleId
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentParseCount
     *
     * @return the value of comment.commentParseCount
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public Integer getCommentParseCount() {
        return commentParseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentParseCount
     *
     * @param commentParseCount the value for comment.commentParseCount
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public void setCommentParseCount(Integer commentParseCount) {
        this.commentParseCount = commentParseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentPutTop
     *
     * @return the value of comment.commentPutTop
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public Integer getCommentPutTop() {
        return commentPutTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentPutTop
     *
     * @param commentPutTop the value for comment.commentPutTop
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public void setCommentPutTop(Integer commentPutTop) {
        this.commentPutTop = commentPutTop;
    }
}