package com.ssdkj.bbs.modular.model;

import java.util.ArrayList;
import java.util.List;

public class CommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public CommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCommentIdIsNull() {
            addCriterion("commentId is null");
            return (Criteria) this;
        }

        public Criteria andCommentIdIsNotNull() {
            addCriterion("commentId is not null");
            return (Criteria) this;
        }

        public Criteria andCommentIdEqualTo(Long value) {
            addCriterion("commentId =", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotEqualTo(Long value) {
            addCriterion("commentId <>", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThan(Long value) {
            addCriterion("commentId >", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("commentId >=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThan(Long value) {
            addCriterion("commentId <", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThanOrEqualTo(Long value) {
            addCriterion("commentId <=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdIn(List<Long> values) {
            addCriterion("commentId in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotIn(List<Long> values) {
            addCriterion("commentId not in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdBetween(Long value1, Long value2) {
            addCriterion("commentId between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotBetween(Long value1, Long value2) {
            addCriterion("commentId not between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentContentIsNull() {
            addCriterion("commentContent is null");
            return (Criteria) this;
        }

        public Criteria andCommentContentIsNotNull() {
            addCriterion("commentContent is not null");
            return (Criteria) this;
        }

        public Criteria andCommentContentEqualTo(String value) {
            addCriterion("commentContent =", value, "commentContent");
            return (Criteria) this;
        }

        public Criteria andCommentContentNotEqualTo(String value) {
            addCriterion("commentContent <>", value, "commentContent");
            return (Criteria) this;
        }

        public Criteria andCommentContentGreaterThan(String value) {
            addCriterion("commentContent >", value, "commentContent");
            return (Criteria) this;
        }

        public Criteria andCommentContentGreaterThanOrEqualTo(String value) {
            addCriterion("commentContent >=", value, "commentContent");
            return (Criteria) this;
        }

        public Criteria andCommentContentLessThan(String value) {
            addCriterion("commentContent <", value, "commentContent");
            return (Criteria) this;
        }

        public Criteria andCommentContentLessThanOrEqualTo(String value) {
            addCriterion("commentContent <=", value, "commentContent");
            return (Criteria) this;
        }

        public Criteria andCommentContentLike(String value) {
            addCriterion("commentContent like", value, "commentContent");
            return (Criteria) this;
        }

        public Criteria andCommentContentNotLike(String value) {
            addCriterion("commentContent not like", value, "commentContent");
            return (Criteria) this;
        }

        public Criteria andCommentContentIn(List<String> values) {
            addCriterion("commentContent in", values, "commentContent");
            return (Criteria) this;
        }

        public Criteria andCommentContentNotIn(List<String> values) {
            addCriterion("commentContent not in", values, "commentContent");
            return (Criteria) this;
        }

        public Criteria andCommentContentBetween(String value1, String value2) {
            addCriterion("commentContent between", value1, value2, "commentContent");
            return (Criteria) this;
        }

        public Criteria andCommentContentNotBetween(String value1, String value2) {
            addCriterion("commentContent not between", value1, value2, "commentContent");
            return (Criteria) this;
        }

        public Criteria andCommentCreateTimeIsNull() {
            addCriterion("commentCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCommentCreateTimeIsNotNull() {
            addCriterion("commentCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCommentCreateTimeEqualTo(String value) {
            addCriterion("commentCreateTime =", value, "commentCreateTime");
            return (Criteria) this;
        }

        public Criteria andCommentCreateTimeNotEqualTo(String value) {
            addCriterion("commentCreateTime <>", value, "commentCreateTime");
            return (Criteria) this;
        }

        public Criteria andCommentCreateTimeGreaterThan(String value) {
            addCriterion("commentCreateTime >", value, "commentCreateTime");
            return (Criteria) this;
        }

        public Criteria andCommentCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("commentCreateTime >=", value, "commentCreateTime");
            return (Criteria) this;
        }

        public Criteria andCommentCreateTimeLessThan(String value) {
            addCriterion("commentCreateTime <", value, "commentCreateTime");
            return (Criteria) this;
        }

        public Criteria andCommentCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("commentCreateTime <=", value, "commentCreateTime");
            return (Criteria) this;
        }

        public Criteria andCommentCreateTimeLike(String value) {
            addCriterion("commentCreateTime like", value, "commentCreateTime");
            return (Criteria) this;
        }

        public Criteria andCommentCreateTimeNotLike(String value) {
            addCriterion("commentCreateTime not like", value, "commentCreateTime");
            return (Criteria) this;
        }

        public Criteria andCommentCreateTimeIn(List<String> values) {
            addCriterion("commentCreateTime in", values, "commentCreateTime");
            return (Criteria) this;
        }

        public Criteria andCommentCreateTimeNotIn(List<String> values) {
            addCriterion("commentCreateTime not in", values, "commentCreateTime");
            return (Criteria) this;
        }

        public Criteria andCommentCreateTimeBetween(String value1, String value2) {
            addCriterion("commentCreateTime between", value1, value2, "commentCreateTime");
            return (Criteria) this;
        }

        public Criteria andCommentCreateTimeNotBetween(String value1, String value2) {
            addCriterion("commentCreateTime not between", value1, value2, "commentCreateTime");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIdIsNull() {
            addCriterion("commentAuthorId is null");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIdIsNotNull() {
            addCriterion("commentAuthorId is not null");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIdEqualTo(Long value) {
            addCriterion("commentAuthorId =", value, "commentAuthorId");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIdNotEqualTo(Long value) {
            addCriterion("commentAuthorId <>", value, "commentAuthorId");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIdGreaterThan(Long value) {
            addCriterion("commentAuthorId >", value, "commentAuthorId");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("commentAuthorId >=", value, "commentAuthorId");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIdLessThan(Long value) {
            addCriterion("commentAuthorId <", value, "commentAuthorId");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIdLessThanOrEqualTo(Long value) {
            addCriterion("commentAuthorId <=", value, "commentAuthorId");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIdIn(List<Long> values) {
            addCriterion("commentAuthorId in", values, "commentAuthorId");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIdNotIn(List<Long> values) {
            addCriterion("commentAuthorId not in", values, "commentAuthorId");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIdBetween(Long value1, Long value2) {
            addCriterion("commentAuthorId between", value1, value2, "commentAuthorId");
            return (Criteria) this;
        }

        public Criteria andCommentAuthorIdNotBetween(Long value1, Long value2) {
            addCriterion("commentAuthorId not between", value1, value2, "commentAuthorId");
            return (Criteria) this;
        }

        public Criteria andCommentNickNameIsNull() {
            addCriterion("commentNickName is null");
            return (Criteria) this;
        }

        public Criteria andCommentNickNameIsNotNull() {
            addCriterion("commentNickName is not null");
            return (Criteria) this;
        }

        public Criteria andCommentNickNameEqualTo(String value) {
            addCriterion("commentNickName =", value, "commentNickName");
            return (Criteria) this;
        }

        public Criteria andCommentNickNameNotEqualTo(String value) {
            addCriterion("commentNickName <>", value, "commentNickName");
            return (Criteria) this;
        }

        public Criteria andCommentNickNameGreaterThan(String value) {
            addCriterion("commentNickName >", value, "commentNickName");
            return (Criteria) this;
        }

        public Criteria andCommentNickNameGreaterThanOrEqualTo(String value) {
            addCriterion("commentNickName >=", value, "commentNickName");
            return (Criteria) this;
        }

        public Criteria andCommentNickNameLessThan(String value) {
            addCriterion("commentNickName <", value, "commentNickName");
            return (Criteria) this;
        }

        public Criteria andCommentNickNameLessThanOrEqualTo(String value) {
            addCriterion("commentNickName <=", value, "commentNickName");
            return (Criteria) this;
        }

        public Criteria andCommentNickNameLike(String value) {
            addCriterion("commentNickName like", value, "commentNickName");
            return (Criteria) this;
        }

        public Criteria andCommentNickNameNotLike(String value) {
            addCriterion("commentNickName not like", value, "commentNickName");
            return (Criteria) this;
        }

        public Criteria andCommentNickNameIn(List<String> values) {
            addCriterion("commentNickName in", values, "commentNickName");
            return (Criteria) this;
        }

        public Criteria andCommentNickNameNotIn(List<String> values) {
            addCriterion("commentNickName not in", values, "commentNickName");
            return (Criteria) this;
        }

        public Criteria andCommentNickNameBetween(String value1, String value2) {
            addCriterion("commentNickName between", value1, value2, "commentNickName");
            return (Criteria) this;
        }

        public Criteria andCommentNickNameNotBetween(String value1, String value2) {
            addCriterion("commentNickName not between", value1, value2, "commentNickName");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlIsNull() {
            addCriterion("headImgurl is null");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlIsNotNull() {
            addCriterion("headImgurl is not null");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlEqualTo(String value) {
            addCriterion("headImgurl =", value, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlNotEqualTo(String value) {
            addCriterion("headImgurl <>", value, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlGreaterThan(String value) {
            addCriterion("headImgurl >", value, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlGreaterThanOrEqualTo(String value) {
            addCriterion("headImgurl >=", value, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlLessThan(String value) {
            addCriterion("headImgurl <", value, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlLessThanOrEqualTo(String value) {
            addCriterion("headImgurl <=", value, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlLike(String value) {
            addCriterion("headImgurl like", value, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlNotLike(String value) {
            addCriterion("headImgurl not like", value, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlIn(List<String> values) {
            addCriterion("headImgurl in", values, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlNotIn(List<String> values) {
            addCriterion("headImgurl not in", values, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlBetween(String value1, String value2) {
            addCriterion("headImgurl between", value1, value2, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andHeadImgurlNotBetween(String value1, String value2) {
            addCriterion("headImgurl not between", value1, value2, "headImgurl");
            return (Criteria) this;
        }

        public Criteria andArticleIdIsNull() {
            addCriterion("articleId is null");
            return (Criteria) this;
        }

        public Criteria andArticleIdIsNotNull() {
            addCriterion("articleId is not null");
            return (Criteria) this;
        }

        public Criteria andArticleIdEqualTo(Long value) {
            addCriterion("articleId =", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotEqualTo(Long value) {
            addCriterion("articleId <>", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdGreaterThan(Long value) {
            addCriterion("articleId >", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdGreaterThanOrEqualTo(Long value) {
            addCriterion("articleId >=", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdLessThan(Long value) {
            addCriterion("articleId <", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdLessThanOrEqualTo(Long value) {
            addCriterion("articleId <=", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdLike(Long value) {
            addCriterion("articleId like", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotLike(Long value) {
            addCriterion("articleId not like", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdIn(List<Long> values) {
            addCriterion("articleId in", values, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotIn(List<Long> values) {
            addCriterion("articleId not in", values, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdBetween(Long value1, Long value2) {
            addCriterion("articleId between", value1, value2, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotBetween(Long value1, Long value2) {
            addCriterion("articleId not between", value1, value2, "articleId");
            return (Criteria) this;
        }

        public Criteria andCommentParseCountIsNull() {
            addCriterion("commentParseCount is null");
            return (Criteria) this;
        }

        public Criteria andCommentParseCountIsNotNull() {
            addCriterion("commentParseCount is not null");
            return (Criteria) this;
        }

        public Criteria andCommentParseCountEqualTo(Integer value) {
            addCriterion("commentParseCount =", value, "commentParseCount");
            return (Criteria) this;
        }

        public Criteria andCommentParseCountNotEqualTo(Integer value) {
            addCriterion("commentParseCount <>", value, "commentParseCount");
            return (Criteria) this;
        }

        public Criteria andCommentParseCountGreaterThan(Integer value) {
            addCriterion("commentParseCount >", value, "commentParseCount");
            return (Criteria) this;
        }

        public Criteria andCommentParseCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("commentParseCount >=", value, "commentParseCount");
            return (Criteria) this;
        }

        public Criteria andCommentParseCountLessThan(Integer value) {
            addCriterion("commentParseCount <", value, "commentParseCount");
            return (Criteria) this;
        }

        public Criteria andCommentParseCountLessThanOrEqualTo(Integer value) {
            addCriterion("commentParseCount <=", value, "commentParseCount");
            return (Criteria) this;
        }

        public Criteria andCommentParseCountIn(List<Integer> values) {
            addCriterion("commentParseCount in", values, "commentParseCount");
            return (Criteria) this;
        }

        public Criteria andCommentParseCountNotIn(List<Integer> values) {
            addCriterion("commentParseCount not in", values, "commentParseCount");
            return (Criteria) this;
        }

        public Criteria andCommentParseCountBetween(Integer value1, Integer value2) {
            addCriterion("commentParseCount between", value1, value2, "commentParseCount");
            return (Criteria) this;
        }

        public Criteria andCommentParseCountNotBetween(Integer value1, Integer value2) {
            addCriterion("commentParseCount not between", value1, value2, "commentParseCount");
            return (Criteria) this;
        }

        public Criteria andCommentPutTopIsNull() {
            addCriterion("commentPutTop is null");
            return (Criteria) this;
        }

        public Criteria andCommentPutTopIsNotNull() {
            addCriterion("commentPutTop is not null");
            return (Criteria) this;
        }

        public Criteria andCommentPutTopEqualTo(Integer value) {
            addCriterion("commentPutTop =", value, "commentPutTop");
            return (Criteria) this;
        }

        public Criteria andCommentPutTopNotEqualTo(Integer value) {
            addCriterion("commentPutTop <>", value, "commentPutTop");
            return (Criteria) this;
        }

        public Criteria andCommentPutTopGreaterThan(Integer value) {
            addCriterion("commentPutTop >", value, "commentPutTop");
            return (Criteria) this;
        }

        public Criteria andCommentPutTopGreaterThanOrEqualTo(Integer value) {
            addCriterion("commentPutTop >=", value, "commentPutTop");
            return (Criteria) this;
        }

        public Criteria andCommentPutTopLessThan(Integer value) {
            addCriterion("commentPutTop <", value, "commentPutTop");
            return (Criteria) this;
        }

        public Criteria andCommentPutTopLessThanOrEqualTo(Integer value) {
            addCriterion("commentPutTop <=", value, "commentPutTop");
            return (Criteria) this;
        }

        public Criteria andCommentPutTopIn(List<Integer> values) {
            addCriterion("commentPutTop in", values, "commentPutTop");
            return (Criteria) this;
        }

        public Criteria andCommentPutTopNotIn(List<Integer> values) {
            addCriterion("commentPutTop not in", values, "commentPutTop");
            return (Criteria) this;
        }

        public Criteria andCommentPutTopBetween(Integer value1, Integer value2) {
            addCriterion("commentPutTop between", value1, value2, "commentPutTop");
            return (Criteria) this;
        }

        public Criteria andCommentPutTopNotBetween(Integer value1, Integer value2) {
            addCriterion("commentPutTop not between", value1, value2, "commentPutTop");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbggenerated do_not_delete_during_merge Mon Oct 14 11:46:09 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbggenerated Mon Oct 14 11:46:09 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}