package com.ssdkj.bbs.modular.model;

import com.ssdkj.bbs.common.annotation.Skip;

public class ParseRecord {

    @Skip
    private int pageNum;
    @Skip
    private int pageSize;

    public int getPageNum() {
        return pageNum;
    }

    public void setPageNum(int pageNum) {
        this.pageNum = pageNum;
    }

    public int getPageSize() {
        return pageSize;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parseRecord.parseId
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    private Long parseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parseRecord.parseAuthorId
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    private Long parseAuthorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parseRecord.articleId
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parseRecord.parseTime
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    private String parseTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parseRecord.parseId
     *
     * @return the value of parseRecord.parseId
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    public Long getParseId() {
        return parseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parseRecord.parseId
     *
     * @param parseId the value for parseRecord.parseId
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    public void setParseId(Long parseId) {
        this.parseId = parseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parseRecord.parseAuthorId
     *
     * @return the value of parseRecord.parseAuthorId
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    public Long getParseAuthorId() {
        return parseAuthorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parseRecord.parseAuthorId
     *
     * @param parseAuthorId the value for parseRecord.parseAuthorId
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    public void setParseAuthorId(Long parseAuthorId) {
        this.parseAuthorId = parseAuthorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parseRecord.articleId
     *
     * @return the value of parseRecord.articleId
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parseRecord.articleId
     *
     * @param articleId the value for parseRecord.articleId
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parseRecord.parseTime
     *
     * @return the value of parseRecord.parseTime
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    public String getParseTime() {
        return parseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parseRecord.parseTime
     *
     * @param parseTime the value for parseRecord.parseTime
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    public void setParseTime(String parseTime) {
        this.parseTime = parseTime;
    }
}