package com.ssdkj.bbs.modular.model;

import com.ssdkj.bbs.common.annotation.Skip;

import java.io.Serializable;

public class User implements Serializable{

    @Skip
    private int pageNum;
    @Skip
    private int pageSize;

    public int getPageNum() {
        return pageNum;
    }

    public void setPageNum(int pageNum) {
        this.pageNum = pageNum;
    }

    public int getPageSize() {
        return pageSize;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userId
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickName
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userSex
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    private Integer userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userRole
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    private String userRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.headImgurl
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    private String headImgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.openId
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.creatTime
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    private String creatTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userId
     *
     * @return the value of user.userId
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userId
     *
     * @param userId the value for user.userId
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickName
     *
     * @return the value of user.nickName
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickName
     *
     * @param nickName the value for user.nickName
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userSex
     *
     * @return the value of user.userSex
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    public Integer getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userSex
     *
     * @param userSex the value for user.userSex
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userRole
     *
     * @return the value of user.userRole
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userRole
     *
     * @param userRole the value for user.userRole
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.headImgurl
     *
     * @return the value of user.headImgurl
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    public String getHeadImgurl() {
        return headImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.headImgurl
     *
     * @param headImgurl the value for user.headImgurl
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    public void setHeadImgurl(String headImgurl) {
        this.headImgurl = headImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.openId
     *
     * @return the value of user.openId
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.openId
     *
     * @param openId the value for user.openId
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.creatTime
     *
     * @return the value of user.creatTime
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    public String getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.creatTime
     *
     * @param creatTime the value for user.creatTime
     *
     * @mbggenerated Tue Oct 08 17:25:29 CST 2019
     */
    public void setCreatTime(String creatTime) {
        this.creatTime = creatTime;
    }
}