package com.ssdkj.bbs.modular.dao;

import com.github.pagehelper.Page;
import com.ssdkj.bbs.modular.model.ParseRecord;
import com.ssdkj.bbs.modular.model.ParseRecordExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component("parseRecordMapper")
public interface ParseRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parseRecord
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    int countByExample(ParseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parseRecord
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    int deleteByExample(ParseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parseRecord
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    int deleteByPrimaryKey(Long parseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parseRecord
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    int insert(ParseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parseRecord
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    int insertSelective(ParseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parseRecord
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    Page<ParseRecord> selectByExample(ParseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parseRecord
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    ParseRecord selectByPrimaryKey(Long parseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parseRecord
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") ParseRecord record, @Param("example") ParseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parseRecord
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    int updateByExample(@Param("record") ParseRecord record, @Param("example") ParseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parseRecord
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    int updateByPrimaryKeySelective(ParseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parseRecord
     *
     * @mbggenerated Mon Oct 14 13:51:24 CST 2019
     */
    int updateByPrimaryKey(ParseRecord record);

}